/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "register_archive.h"

bool_t
xdr_client_rpc (XDR *xdrs, client_rpc *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_opaque (xdrs, objp->user_name, 255))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->last_message_id))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->error_code))
		 return FALSE;
	return TRUE;
}
