/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "register_archive.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
register_1(char *user_name, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, REGISTER,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user_name,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unregister_1(char *user_name, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, UNREGISTER,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user_name,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
find_1(char *user_name, client_rpc *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, FIND,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user_name,
		(xdrproc_t) xdr_client_rpc, (caddr_t) clnt_res,
		TIMEOUT));
}
