/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REGISTER_ARCHIVE_H_RPCGEN
#define _REGISTER_ARCHIVE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct client_rpc {
	char user_name[255];
	u_int last_message_id;
	char error_code;
};
typedef struct client_rpc client_rpc;

#define register_archive 99
#define register_archive1 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTER 2
extern  enum clnt_stat register_1(char *, int *, CLIENT *);
extern  bool_t register_1_svc(char *, int *, struct svc_req *);
#define UNREGISTER 3
extern  enum clnt_stat unregister_1(char *, int *, CLIENT *);
extern  bool_t unregister_1_svc(char *, int *, struct svc_req *);
#define FIND 4
extern  enum clnt_stat find_1(char *, client_rpc *, CLIENT *);
extern  bool_t find_1_svc(char *, client_rpc *, struct svc_req *);
extern int register_archive_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTER 2
extern  enum clnt_stat register_1();
extern  bool_t register_1_svc();
#define UNREGISTER 3
extern  enum clnt_stat unregister_1();
extern  bool_t unregister_1_svc();
#define FIND 4
extern  enum clnt_stat find_1();
extern  bool_t find_1_svc();
extern int register_archive_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_client_rpc (XDR *, client_rpc*);

#else /* K&R C */
extern bool_t xdr_client_rpc ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REGISTER_ARCHIVE_H_RPCGEN */
