
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TextConversorServiceService", targetNamespace = "http://textConversor/", wsdlLocation = "file:/work/sd_practica_final/WebService/TextConversorServiceService.wsdl")
public class TextConversorServiceService
    extends Service
{

    private final static URL TEXTCONVERSORSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TEXTCONVERSORSERVICESERVICE_EXCEPTION;
    private final static QName TEXTCONVERSORSERVICESERVICE_QNAME = new QName("http://textConversor/", "TextConversorServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/work/sd_practica_final/WebService/TextConversorServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEXTCONVERSORSERVICESERVICE_WSDL_LOCATION = url;
        TEXTCONVERSORSERVICESERVICE_EXCEPTION = e;
    }

    public TextConversorServiceService() {
        super(__getWsdlLocation(), TEXTCONVERSORSERVICESERVICE_QNAME);
    }

    public TextConversorServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEXTCONVERSORSERVICESERVICE_QNAME, features);
    }

    public TextConversorServiceService(URL wsdlLocation) {
        super(wsdlLocation, TEXTCONVERSORSERVICESERVICE_QNAME);
    }

    public TextConversorServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEXTCONVERSORSERVICESERVICE_QNAME, features);
    }

    public TextConversorServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TextConversorServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TextConversorService
     */
    @WebEndpoint(name = "TextConversorServicePort")
    public TextConversorService getTextConversorServicePort() {
        return super.getPort(new QName("http://textConversor/", "TextConversorServicePort"), TextConversorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TextConversorService
     */
    @WebEndpoint(name = "TextConversorServicePort")
    public TextConversorService getTextConversorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://textConversor/", "TextConversorServicePort"), TextConversorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEXTCONVERSORSERVICESERVICE_EXCEPTION!= null) {
            throw TEXTCONVERSORSERVICESERVICE_EXCEPTION;
        }
        return TEXTCONVERSORSERVICESERVICE_WSDL_LOCATION;
    }

}
